---
title: "Vasile Draganescu Popovici"
format: html
---

# Question 1
```{r}
library(here)
library(readr)

here::i_am("lab-grades.Rproj")
courses <- read_csv(here("data", "courses.csv"))
```
# Question 2
```{r}
library(dplyr)
library(knitr)

courses |>
rename(`course name` = course, identifier = course_id, module = module,
       `number of exams` = nb_grades) |>
arrange(`course name`) |>
kable()
```
# Question 3
```{r}
students <- read_csv(here("data", "students.csv"))
```
The birth_date column of the students data frame is of class `r class(students$birth_date)`.
The sex column of the students data frame is of class `r class(students$sex)`.

# Quesiton 4
```{r}
grades <- read_delim(here("data", "grades.csv"), delim = "|", na = "$")
```
# Question 5
```{r}
library(ggplot2)

students |>
ggplot(aes(x = factor(group))) +
geom_bar() +
xlab("Group") +
ylab("Number of students") +
theme_minimal()

```
# Question 6
```{r}
students |>
ggplot(aes(x = factor(group), fill = sex)) +
geom_bar(position = "fill") +
scale_fill_manual(values = c("salmon", "steelblue")) +
theme_minimal()
```
# Question 7
```{r}
library(lubridate)

students_age <- students |>
mutate(age = time_length(today() - birth_date, unit = "year"))

students_age |>
ggplot(aes(x = age)) +
geom_histogram(binwidth = 1, fill = "cyan", color = "white") +
xlab("Age") +
ylab("Number of students") +
theme_minimal()
```
# Question 8 
```{r}
median_age <- students |>
mutate(age = time_length(today() - birth_date, unit = "year")) |>
group_by(group) |>
summarise(median_age = round(median(age)))

median_age |>
knitr::kable()
```
# Question 9
```{r}
oldest <- students |>
mutate(age = time_length(today() - birth_date, unit = "year")) |>
group_by(group) |>
slice_max(age, n = 1) |>
ungroup() |>
select(id, sex, age, group) |>
arrange(desc(age))

oldest |>
knitr::kable()
```


